### ISSUE TITLE
Task List 中的 Checkbox 没有正确渲染

### ISSUE THREAD

**Issue by ocavue** [geeknote-net/feedback#1]
`- [x]` 对应的 checkbox 没有渲染为一个被勾选的勾选框

![CleanShot 2021-07-02 at 20 51 17](https://user-images.githubusercontent.com/24715727/124277133-4a5afc00-db77-11eb-9577-cb3bb2c5537d.png)

**Comment by chloerei** [comment]
这个是 GitHub 的扩展语法，当初考虑到 GeekNote 不是项目管理工具，tasklist 作用不大就没加。

需要更多反馈，写文章的时候 tasklist 是否有需要？

**Comment by ocavue** [comment]
如果只是考虑到写文章的场景，task list 的确未必是常见的需求。不过现在的实现中还是会将 `[ ]` 渲染为 checkbox，所以这里可能需要修改一下。

**Comment by chloerei** [comment]
我搞错了，原来之前已经打开了这个特性，只是 sanitize 的时候把 checked 属性去掉了，现已修复。
