### ISSUE TITLE
部分图片会出现 404 的情况

### ISSUE THREAD

**Issue by ocavue** [geeknote-net/feedback#2]
比如这张 `/attachments/4rCdDvvB1Wxv7uHiTBRhr5CS/Screenshot%202021-07-02%20at%208.56.28%20PM.png`

![CleanShot 2021-07-02 at 20 58 46](https://user-images.githubusercontent.com/24715727/124278045-5a271000-db78-11eb-981f-2cef3c834d8b.png)

**Comment by chloerei** [comment]
修复了，路由规则没写好。

因为缓存的原因强制刷新一下就能看到。
