### ISSUE TITLE
个人合集页面布局

### ISSUE THREAD

**Issue by iuhoay** [geeknote-net/feedback#27]
![image](https://user-images.githubusercontent.com/749699/206093672-f132c7e1-3f6f-48e5-9e69-e59421101876.png)

没有统一加上 padding

**Comment by chloerei** [comment]
<img width="849" alt="截屏2023-01-11 21 03 40" src="https://user-images.githubusercontent.com/49931/211813314-02d59c5b-8166-4357-8cbf-3a1868775544.png">

已修复
