### ISSUE TITLE
在测试导出Markdown格式的文章和附件功能时发现图片无法正常下载

### ISSUE THREAD

**Issue by helloobaby** [geeknote-net/feedback#29]
下载下来有三个文件夹，attachments文件夹为空，应该不是网络问题，我试了好几次

**Comment by chloerei** [comment]
要在本站上传的图片这个文件夹才会有内容，外链的不会导出。

具体是哪篇文章有问题可以发地址来分析下。

**Comment by helloobaby** [comment]
下面这篇，这算外链吗，我直接复制粘贴上来的，markdown里显示路径是在attachments里
`https://geeknote.net/aoteman/posts/2021`

**Comment by chloerei** [comment]
发现问题了，是 bug。修复需要一些时间，修好了我再回复。

**Comment by helloobaby** [comment]
好，感谢作者

**Comment by chloerei** [comment]
修复了，可以再试试。

**Comment by helloobaby** [comment]
图片可以正常下载了，但是还有个小bug
比如在web端在线编辑的markdown中，图片路径是这样的
`![image.png](/attachments/NwDnPcJaQwhty9dPB5n3sN3Q/image.png)`，
但是如果是下载下来的话，路径应该是
`![image.png](../attachments/NwDnPcJaQwhty9dPB5n3sN3Q/image.png)`，

**Comment by helloobaby** [comment]
解决方法的话有一个是把post里的markdown文件放到根目录就好了，不用在post里面

**Comment by chloerei** [comment]
用支持项目目录的编辑器例如 vscode，在导出文件夹的根目录打开，可以识别绝对路径。这个路径在迁移到静态网站的时候比较方便，暂时不打算修改。有必要的可以写个脚本或者编辑器的批量修改替换一下。

**Comment by helloobaby** [comment]
可以，这个问题不大，一般都在web端看看

**Comment by chloerei** [comment]
好的，多谢反馈。👍
