### ISSUE TITLE
改了用户名，但是主页显示的名字没改，点内容进去名字是改的

### ISSUE THREAD

**Issue by helloobaby** [geeknote-net/feedback#31]
![image](https://user-images.githubusercontent.com/84119280/220545425-03d765f0-7a36-4505-9ab9-3174732a16a0.png)
![image](https://user-images.githubusercontent.com/84119280/220545462-21db9a3a-3dca-497a-aed3-5ca3d9cc03f1.png)
如图，是bug吗。

**Comment by chloerei** [comment]
缓存机制的问题，已修复。
